openapi: 3.0.1
info:
  title: Hallucination Checker
  description: API to check if claims in a response are supported by online evidence
  version: "1.0.0"
servers:
  - url: https://your-domain.com
paths:
  /check:
    post:
      summary: Check GPT response for hallucinations
      operationId: checkHallucinations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                response:
                  type: string
                  description: ChatGPT-generated answer to evaluate
      responses:
        "200":
          description: Claim analysis result
          content:
            application/json:
              schema:
                type: object
                properties:
                  claims:
                    type: array
                    items:
                      type: object
                      properties:
                        text:
                          type: string
                        supported:
                          type: boolean
                        score:
                          type: number